const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const W=900,H=600,S={x:145,y:428},GRAVITY=450,MAX_PULL=125,POWER=8.15,STORAGE='davids-sling-v1';
const scripture=[
 ['1 Samuel 17:47','God can save without a sword or spear.'],['1 Samuel 16:7','God looks at the heart.'],['Joshua 1:9','Be brave; the Lord goes with you.'],['Psalm 27:1','The Lord is your light and strength.'],['Psalm 56:3','When afraid, trust God.'],['Isaiah 41:10','God will strengthen and help you.'],['Proverbs 3:5','Trust the Lord with your whole heart.'],['Psalm 23:1','The Lord cares for His sheep.'],['Philippians 4:13','Christ gives strength for what He calls us to do.'],['Romans 8:31','God is for His people.'],
 ['Psalm 46:1','God is a present refuge in trouble.'],['Deuteronomy 31:6','The Lord will not leave you.'],['Psalm 34:4','The Lord hears and frees us from fear.'],['Matthew 19:26','With God, all things are possible.'],['Mark 10:27','What seems impossible to us is possible with God.'],['Ephesians 6:10','Be strong in the Lord.'],['Psalm 118:6','The Lord is with us; we need not fear.'],['2 Timothy 1:7','God gives power, love, and self-control.'],['Psalm 121:2','Our help comes from the Lord.'],['Isaiah 40:31','Those who hope in the Lord receive renewed strength.'],
 ['Psalm 37:5','Commit your way to the Lord.'],['James 1:5','Ask God for wisdom.'],['Proverbs 16:3','Entrust your work to the Lord.'],['Psalm 119:105','God’s word lights the path.'],['Micah 6:8','Do justice, love mercy, walk humbly.'],['Galatians 6:9','Do not grow tired of doing good.'],['1 Corinthians 16:13','Stand firm in faith and be courageous.'],['Psalm 31:24','Take heart as you hope in the Lord.'],['Hebrews 12:1','Keep running with endurance.'],['Colossians 3:23','Work wholeheartedly for the Lord.'],
 ['Matthew 5:16','Let your good deeds point others to God.'],['John 8:12','Jesus is the light of the world.'],['John 14:6','Jesus is the way, truth, and life.'],['John 3:16','God loved the world and gave His Son.'],['Ephesians 2:8','Salvation is God’s gift through faith.'],['Romans 5:8','Christ died for us while we were sinners.'],['1 John 4:19','We love because God loved us first.'],['Matthew 22:39','Love your neighbor as yourself.'],['Luke 6:31','Treat others the way you wish to be treated.'],['Philippians 2:4','Look to the interests of others.'],
 ['Romans 12:12','Be joyful in hope and faithful in prayer.'],['1 Thessalonians 5:17','Keep praying.'],['Matthew 7:7','Ask, seek, and knock.'],['Jeremiah 29:12','Call on God; He hears prayer.'],['Psalm 55:22','Give your burdens to the Lord.'],['1 Peter 5:7','Cast your worries on God because He cares.'],['Philippians 4:6','Bring every concern to God in prayer.'],['Philippians 4:7','God’s peace guards hearts and minds.'],['John 14:27','Jesus gives His peace.'],['Isaiah 26:3','Trusting God brings steady peace.'],
 ['Psalm 4:8','God lets His people rest in safety.'],['Psalm 91:2','The Lord is our refuge.'],['Proverbs 18:10','The Lord’s name is a strong tower.'],['Psalm 18:2','The Lord is rock, fortress, and rescuer.'],['Nahum 1:7','The Lord cares for those who trust Him.'],['Psalm 62:6','God is our rock and salvation.'],['Psalm 73:26','God is the strength of our hearts.'],['Habakkuk 3:19','The Lord gives strength to keep going.'],['2 Corinthians 12:9','God’s grace is enough.'],['Hebrews 4:16','Come boldly to God for mercy and grace.'],
 ['Lamentations 3:22','God’s mercies do not run out.'],['Lamentations 3:23','His mercies are new each morning.'],['Psalm 103:8','The Lord is compassionate and gracious.'],['Psalm 145:9','The Lord is good to all.'],['Psalm 100:5','The Lord is good; His love endures.'],['Psalm 136:1','Give thanks: God’s faithful love endures.'],['James 1:17','Every good gift comes from above.'],['1 Thessalonians 5:18','Give thanks in every circumstance.'],['Psalm 107:1','Thank the Lord for His enduring love.'],['Colossians 3:15','Let Christ’s peace rule in your heart.'],
 ['Colossians 3:17','Do all things in Jesus’ name with thanks.'],['Romans 15:13','God fills His people with joy and peace.'],['Nehemiah 8:10','The Lord’s joy is strength.'],['Psalm 16:11','God shows the path of life and joy.'],['John 15:11','Jesus wants His joy in His disciples.'],['Philippians 4:4','Rejoice in the Lord.'],['Psalm 30:5','Joy comes in the morning.'],['Romans 12:21','Overcome evil with good.'],['Ephesians 4:32','Be kind and forgiving.'],['Galatians 5:22','God’s Spirit grows love, joy, and peace.'],
 ['Galatians 5:23','God’s Spirit grows gentleness and self-control.'],['1 Corinthians 13:4','Love is patient and kind.'],['1 John 3:18','Love through actions and truth.'],['Proverbs 17:17','A friend loves at all times.'],['John 13:34','Jesus calls us to love one another.'],['Matthew 5:9','God blesses peacemakers.'],['Romans 12:18','As far as you can, live at peace.'],['Hebrews 13:16','Keep doing good and sharing.'],['Proverbs 19:17','Kindness to the poor matters to the Lord.'],['Matthew 25:40','Serving the overlooked matters to Jesus.'],
 ['Luke 15:4','The shepherd seeks the missing sheep.'],['Luke 15:7','Heaven rejoices when a sinner turns back.'],['John 10:11','Jesus is the good shepherd.'],['John 10:14','Jesus knows His sheep.'],['John 10:27','His sheep listen to His voice.'],['John 10:28','Jesus holds His people securely.'],['Revelation 21:4','God will wipe away every tear.'],['Revelation 22:5','The Lord’s light will shine forever.'],['Romans 8:39','Nothing can separate us from God’s love in Christ.']
];
const scenes=[
 {name:'Sunrise Valley',top:'#457c89',mid:'#d8c18b',far:'#547f78',near:'#375f52',ground:'#b99160',sun:'#fff1ba'},
 {name:'Olive Grove',top:'#426874',mid:'#c9d5ab',far:'#658277',near:'#355d47',ground:'#a88b59',sun:'#f9e3ab'},
 {name:'Desert Dawn',top:'#b97e68',mid:'#f2c996',far:'#b88868',near:'#886d52',ground:'#cfaa6e',sun:'#ffe4a1'},
 {name:'Highland Pass',top:'#405f82',mid:'#9ac0bb',far:'#658194',near:'#405f71',ground:'#a99176',sun:'#f4e4bf'},
 {name:'Twilight Ridge',top:'#333d68',mid:'#a87e98',far:'#5f617b',near:'#3a4d67',ground:'#947467',sun:'#ffe7bc'},
 {name:'Riverlands',top:'#438e9b',mid:'#b0d2bd',far:'#699b89',near:'#367b71',ground:'#b9a67a',sun:'#fff0c2'},
 {name:'Golden Fields',top:'#6d8275',mid:'#dfc58b',far:'#868d70',near:'#58705d',ground:'#c6a365',sun:'#fff0b2'},
 {name:'Star Valley',top:'#243455',mid:'#6b779a',far:'#4c607b',near:'#2c5364',ground:'#8b8071',sun:'#fff0cc'},
 {name:'Homeward Hills',top:'#5f7c67',mid:'#d3caa0',far:'#738f70',near:'#486b59',ground:'#b49b6c',sun:'#ffedb8'}
];
const firstEight=[
 {name:'The first stone',hint:'Pull back from the sling and strike the gold emblem.',target:{x:704,y:305,r:36},wind:0},
 {name:'A higher aim',hint:'Draw farther down to send the stone higher.',target:{x:735,y:224,r:34},wind:0},
 {name:'Beyond the wall',hint:'Arc over the low stone wall.',target:{x:724,y:305,r:34},walls:[{x:447,y:361,w:42,h:166}],wind:0},
 {name:'A moving mark',hint:'Watch the shield rise and fall. Time your release.',target:{x:730,y:287,r:33,move:62,speed:1.65},wind:0},
 {name:'Across the valley',hint:'The shadow bird swoops across the valley. Watch its path.',target:{x:808,y:301,r:34},walls:[{x:520,y:411,w:60,h:114}],bird:{speed:215,offset:0},wind:0},
 {name:'The west wind',hint:'Aim through the wind, and wait for the bird to pass.',target:{x:734,y:291,r:34},bird:{speed:255,offset:300},wind:-105},
 {name:'Narrow opening',hint:'Find an arc above the wall while the bird swoops.',target:{x:765,y:257,r:32},walls:[{x:435,y:385,w:45,h:142},{x:602,y:431,w:52,h:96}],bird:{speed:240,offset:620},wind:30},
 {name:'One faithful shot',hint:'Moving shield, wind, wall, and bird. You are ready.',target:{x:762,y:268,r:34,move:49,speed:1.9},walls:[{x:495,y:400,w:51,h:127}],bird:{speed:280,offset:160},wind:-70}
];
const levels=scripture.map(([ref,message],i)=>{
 const base=i<8?firstEight[i]:{name:`${scenes[i%scenes.length].name} · ${i+1}`,hint:i%4===0?'Watch the sky, then release.':i%4===1?'Follow the moving emblem.':i%4===2?'Arc over the ancient stones.':'Time your shot through the valley.',target:{x:720+(i%4)*18,y:245+(i%3)*24,r:36,move:i%4===0?0:25+(i%3)*12,speed:1.1+(i%4)*.24},walls:i%3===0?[{x:430+(i%2)*55,y:385,w:40,h:140}]:[],bird:{speed:195+(i%4)*20,offset:i*127},wind:(i%5-2)*24};
 return {...base,ref,verse:message,scene:scenes[i%scenes.length],bird:i>=12?{...base.bird,from:i%3===0?'left':i%3===1?'right':'diagonal'}:base.bird};
});
let unlocked=0,cleared={};try{let d=JSON.parse(localStorage.getItem(STORAGE)||'{}');unlocked=Math.max(0,Math.min(levels.length-1,d.unlocked||0));cleared=d.cleared||{}}catch{}
let level=0,shots=3,stone=null,dragging=false,pull={x:0,y:0},finished=false,won=false,locked=false,animTime=0,last=0,windParticles=[],sound=true,audioCtx=null,hitFlash=0,birdAlert=0;
const birdImage=new Image();birdImage.src='./assets/shadow-bird.png';const staffImage=new Image();staffImage.src='./assets/sling-staff.png';const shieldImage=new Image();shieldImage.src='./assets/shield-target.png';const wallImage=new Image();wallImage.src='./assets/stone-wall.png';const stoneImage=new Image();stoneImage.src='./assets/river-stone.png';const sceneImages=['valley-sunrise','valley-grove','valley-night'].map(name=>{let img=new Image();img.src=`./assets/${name}.png`;return img});let portrait=false;
const $=s=>document.querySelector(s);const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const terrain=[{x:0,y:455},{x:105,y:459},{x:240,y:491},{x:395,y:515},{x:590,y:523},{x:900,y:500}];
function store(){try{localStorage.setItem(STORAGE,JSON.stringify({unlocked,cleared}))}catch{}}
function tone(freq=400,duration=.15,type='sine'){if(!sound)return;try{audioCtx??=new (window.AudioContext||window.webkitAudioContext)();let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,audioCtx.currentTime);g.gain.setValueAtTime(.12,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+duration)}catch{}}
function targetAt(t=animTime){let q=levels[level].target;return {x:q.x+(level>=8&&level%4===2?(q.move||0)*.55*Math.cos(t*(q.speed||1)):0),y:q.y+(q.move||0)*Math.sin(t*(q.speed||1)),r:q.r}}
function setLevel(n){level=n;shots=3;stone=null;dragging=false;finished=false;won=false;locked=false;hitFlash=0;birdAlert=0;$('#overlay').classList.add('hidden');$('#levelName').textContent=levels[n].name;$('#levelHint').textContent=levels[n].hint;$('#levelCount').textContent=`LEVEL ${String(n+1).padStart(2,'0')} / ${levels.length}`;$('#chapterVerse').textContent=levels[n].verse;$('#chapterRef').textContent=`— ${levels[n].ref}`;$('#sceneName').textContent=levels[n].scene.name;$('#expandedVerse').textContent=`${levels[n].verse} — ${levels[n].ref}`;updateShots();buttons()}
function updateShots(){$('#shotCount').textContent='● '.repeat(shots).trim()||'NO STONES'}
function buttons(){$('#levelButtons').innerHTML=levels.map((_,i)=>`<button data-level="${i}" class="${i===level?'active':''} ${cleared[i]?'cleared':''}" ${i>unlocked?'disabled':''} aria-label="Level ${i+1}${i>unlocked?' locked':''}">${cleared[i]?'✦':i+1}</button>`).join('');$('#progressText').textContent=`${Object.keys(cleared).length} / ${levels.length} cleared`}
function resetShot(){stone=null;locked=false;if(shots===0&&!finished)end(false)}
function end(win){finished=true;won=win;locked=true;$('#overlay').classList.remove('hidden');if(win){const stars=shots===3?3:shots===2?2:1;cleared[level]=Math.max(stars,cleared[level]||0);unlocked=Math.max(unlocked,Math.min(levels.length-1,level+1));store();$('#overlayKicker').textContent='CHALLENGE CLEARED';$('#stars').textContent='✦ '.repeat(stars).trim()+' ☆ '.repeat(3-stars).trim();$('#overlayTitle').textContent=level===levels.length-1?'The valley is yours!':'A faithful shot!';$('#overlayText').textContent=`${levels[level].verse} — ${levels[level].ref}`;$('#nextBtn').innerHTML=level===levels.length-1?'Play again <span>↻</span>':'Next challenge <span>→</span>';tone(523,.2);setTimeout(()=>tone(659,.24),120);setTimeout(()=>tone(784,.4),260)}else{$('#overlayKicker').textContent='THREE STONES THROWN';$('#stars').textContent='◇ ◇ ◇';$('#overlayTitle').textContent='Try a new angle';$('#overlayText').textContent='Watch the dotted arc. A little more or less pull can change everything.';$('#nextBtn').innerHTML='Try again <span>↻</span>';tone(190,.3,'triangle')}buttons()}
function project(x,y){return portrait?{x:80+(x-S.x)*.52,y:800+(y-S.y)*1.2-(x-S.x)*.36}:{x,y}}function coords(e){let r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*canvas.width/r.width,y=(e.clientY-r.top)*canvas.height/r.height;if(!portrait)return{x,y};let wx=S.x+(x-80)/.52;return{x:wx,y:S.y+(y-800+(wx-S.x)*.36)/1.2}}function setCanvasMode(){portrait=document.querySelector('.arena-wrap').classList.contains('expanded')&&matchMedia('(orientation: portrait)').matches;canvas.width=portrait?500:900;canvas.height=portrait?1000:600;$('#fullBtn').textContent=document.querySelector('.arena-wrap').classList.contains('expanded')?'✕ Close':'⛶ Expand'}window.addEventListener('resize',setCanvasMode);
function onDown(e){if(finished||locked)return;let p=coords(e);if(Math.hypot(p.x-S.x,p.y-S.y)>180)return;dragging=true;canvas.setPointerCapture(e.pointerId);movePull(p);e.preventDefault()}
function movePull(p){let dx=clamp(p.x-S.x,-MAX_PULL,35),dy=clamp(p.y-S.y,-45,MAX_PULL);let len=Math.hypot(dx,dy);if(len>MAX_PULL){dx*=MAX_PULL/len;dy*=MAX_PULL/len}pull={x:dx,y:dy}}
function onMove(e){if(!dragging)return;movePull(coords(e));e.preventDefault()}
function onUp(e){if(!dragging)return;dragging=false;try{canvas.releasePointerCapture(e.pointerId)}catch{}let length=Math.hypot(pull.x,pull.y);if(length<17||pull.x>-14){pull={x:0,y:0};return}stone={x:S.x+pull.x*.4,y:S.y+pull.y*.4,vx:-pull.x*POWER,vy:-pull.y*POWER,r:10,age:0,bounces:0,trail:[]};pull={x:0,y:0};shots--;updateShots();locked=true;tone(200,.09,'triangle');setTimeout(()=>tone(330,.08,'triangle'),65);e.preventDefault()}
canvas.addEventListener('pointerdown',onDown);canvas.addEventListener('pointermove',onMove);canvas.addEventListener('pointerup',onUp);canvas.addEventListener('pointercancel',()=>{dragging=false;pull={x:0,y:0}});
function segmentCircle(a,b,c,r){let dx=b.x-a.x,dy=b.y-a.y,t=clamp(((c.x-a.x)*dx+(c.y-a.y)*dy)/(dx*dx+dy*dy||1),0,1);return Math.hypot(a.x+dx*t-c.x,a.y+dy*t-c.y)<r}
function birdAt(t=animTime,second=false){let b=levels[level].bird;if(!b||second&&level<24)return null;let phase=(t*(second?b.speed*.82:b.speed)+b.offset+(second?590:0))%1260;let direction=second?'left':b.from;let x=direction==='left'?-130+phase:1000-phase;let y=direction==='diagonal'?70+phase*.27+20*Math.sin(t*3):124+190*Math.exp(-Math.pow((x-515)/205,2))+14*Math.sin(t*(second?3:4));if(second)y+=68;return{x,y,rx:44,ry:26,flip:direction==='left'}}
function birdCatches(a,b,q){if(!q)return false;let dx=b.x-a.x,dy=b.y-a.y,t=clamp(((q.x-a.x)*dx+(q.y-a.y)*dy)/(dx*dx+dy*dy||1),0,1);let x=a.x+dx*t,y=a.y+dy*t;return Math.pow((x-q.x)/(q.rx+8),2)+Math.pow((y-q.y)/(q.ry+8),2)<1}
function step(dt){animTime+=dt;hitFlash=Math.max(0,hitFlash-dt*2.5);birdAlert=Math.max(0,birdAlert-dt);if(!stone)return;let p=stone,old={x:p.x,y:p.y};p.vx+=levels[level].wind*dt;p.vy+=GRAVITY*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.age+=dt;p.trail.push({x:p.x,y:p.y});if(p.trail.length>18)p.trail.shift();let q=targetAt();if(segmentCircle(old,p,q,q.r+p.r-5)){stone=null;hitFlash=1;end(true);return}
 if(birdCatches(old,p,birdAt())||birdCatches(old,p,birdAt(animTime,true))){stone=null;birdAlert=1.45;hitFlash=.5;tone(130,.18,'sawtooth');const spent=shots;setTimeout(()=>{if(shots===spent&&!stone&&!finished)resetShot()},650);return}
 for(let wall of levels[level].walls||[]){if(p.x+p.r>wall.x&&p.x-p.r<wall.x+wall.w&&p.y+p.r>wall.y&&p.y-p.r<wall.y+wall.h){if(old.x+10<=wall.x||old.x-10>=wall.x+wall.w){p.vx*=-.48;p.x=old.x}else{p.vy*=-.5;p.y=old.y}p.bounces++;tone(135,.1,'square');break}}
 if(p.y>528||p.x>930||p.x<-30||p.age>3.2||p.bounces>2){stone=null;hitFlash=.35;tone(105,.16,'triangle');setTimeout(resetShot,580)}}
function sky(){let img=sceneImages[Math.floor(level/3)%sceneImages.length],cw=canvas.width,ch=canvas.height;if(img.complete&&img.naturalWidth){let scale=Math.max(cw/img.width,ch/img.height),dw=img.width*scale,dh=img.height*scale;ctx.drawImage(img,(cw-dw)/2,(ch-dh)/2,dw,dh)}else{let g=ctx.createLinearGradient(0,0,0,ch);g.addColorStop(0,levels[level].scene.top);g.addColorStop(1,levels[level].scene.ground);ctx.fillStyle=g;ctx.fillRect(0,0,cw,ch)}ctx.fillStyle=portrait?'#091b220e':'#091b2216';ctx.fillRect(0,0,cw,ch)}
function ground(){} // The illustrated landscape supplies the terrain.
function drawWall(w){let p=project(w.x+w.w/2,w.y+w.h/2),ww=w.w*(portrait?1.2:2.0),hh=w.h*(portrait?1.15:1.2);ctx.save();ctx.shadowColor='#0c1717ad';ctx.shadowBlur=14;ctx.shadowOffsetX=7;if(wallImage.complete&&wallImage.naturalWidth)ctx.drawImage(wallImage,p.x-ww/2,p.y-hh/2,ww,hh);else{ctx.fillStyle='#8a8070';ctx.fillRect(p.x-ww/2,p.y-hh/2,ww,hh)}ctx.restore()}
function shield(){let q=targetAt(),p=project(q.x,q.y),size=(q.r+25)*(portrait?2.3:2.8)*(1+Math.sin(animTime*3)*.025);ctx.save();ctx.translate(p.x,p.y);ctx.shadowColor='#ffe1a0bb';ctx.shadowBlur=25;if(shieldImage.complete&&shieldImage.naturalWidth)ctx.drawImage(shieldImage,-size/2,-size/2,size,size);else{ctx.fillStyle='#d1a660';ctx.beginPath();ctx.arc(0,0,size*.45,0,7);ctx.fill()}ctx.restore()}
function drawBird(second=false){let b=birdAt(animTime,second);if(!b||b.x<-100||b.x>1000)return;ctx.save();let bp=project(b.x,b.y);ctx.translate(bp.x,bp.y);if(b.flip)ctx.scale(-1,1);ctx.rotate(-.07*Math.sin(animTime*5));ctx.shadowColor='#231b39';ctx.shadowBlur=14;if(birdImage.complete&&birdImage.naturalWidth)ctx.drawImage(birdImage,-75,-50,150,100);else{ctx.fillStyle='#292537';ctx.beginPath();ctx.ellipse(0,0,50,25,0,0,7);ctx.fill()}ctx.restore()}
function sling(){let p=project(S.x,S.y),size=portrait?160:165,tipY=p.y-size*.47,tipX=size*.25,pouch=dragging?project(S.x+pull.x,S.y+pull.y-8):project(S.x,S.y-28);ctx.save();ctx.translate(p.x,p.y);ctx.shadowColor='#20180f99';ctx.shadowBlur=14;if(staffImage.complete&&staffImage.naturalWidth)ctx.drawImage(staffImage,-size*.34,-size*.52,size*.68,size);else{ctx.strokeStyle='#a66f3f';ctx.lineWidth=17;ctx.beginPath();ctx.moveTo(0,size*.48);ctx.lineTo(0,0);ctx.lineTo(-tipX,tipY);ctx.moveTo(0,0);ctx.lineTo(tipX,tipY);ctx.stroke()}ctx.restore();ctx.save();ctx.strokeStyle='#533724';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(p.x-tipX*.76,tipY+8);ctx.lineTo(pouch.x,pouch.y);ctx.lineTo(p.x+tipX*.76,tipY+8);ctx.stroke();ctx.fillStyle='#72472b';ctx.beginPath();ctx.ellipse(pouch.x,pouch.y,portrait?12:14,8,0,0,7);ctx.fill();if(!stone&&!dragging&&!locked){if(stoneImage.complete&&stoneImage.naturalWidth)ctx.drawImage(stoneImage,pouch.x-12,pouch.y-12,24,24);else{ctx.fillStyle='#e7d0a4';ctx.beginPath();ctx.arc(pouch.x,pouch.y,9,0,7);ctx.fill()}}ctx.restore()}
function trajectory(){if(!dragging||pull.x>-14)return;let vx=-pull.x*POWER,vy=-pull.y*POWER,x=S.x+pull.x*.4,y=S.y+pull.y*.4;ctx.save();for(let i=0;i<33;i++){let dt=.045;vx+=levels[level].wind*dt;vy+=GRAVITY*dt;x+=vx*dt;y+=vy*dt;if(y>530||x>900)break;let q=project(x,y);ctx.fillStyle=`rgba(255,247,218,${.82-i*.019})`;ctx.beginPath();ctx.arc(q.x,q.y,Math.max(2.1,5-i*.08),0,7);ctx.fill()}ctx.restore()}
function particles(){let w=levels[level].wind;if(!w)return;ctx.fillStyle='#f9e7bb88';for(let i=0;i<11;i++){let x=((i*173+animTime*w*.65)%950+950)%950-25,y=102+(i*73)%345,p=project(x,y);ctx.fillRect(p.x,p.y,17,2)}}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);sky();ground();particles();for(let wall of levels[level].walls||[])drawWall(wall);shield();drawBird();if(level>=24)drawBird(true);trajectory();sling();if(stone){ctx.save();for(let i=0;i<stone.trail.length;i++){let p=project(stone.trail[i].x,stone.trail[i].y);ctx.fillStyle=`rgba(255,233,182,${i/stone.trail.length*.45})`;ctx.beginPath();ctx.arc(p.x,p.y,3+i/stone.trail.length*4,0,7);ctx.fill()}let p=project(stone.x,stone.y);ctx.shadowColor='#fff0a9';ctx.shadowBlur=17;if(stoneImage.complete&&stoneImage.naturalWidth)ctx.drawImage(stoneImage,p.x-16,p.y-15,32,30);else{ctx.fillStyle='#eee0b2';ctx.beginPath();ctx.arc(p.x,p.y,stone.r,0,7);ctx.fill()}ctx.restore()}if(hitFlash>0){ctx.fillStyle=`rgba(255,238,180,${hitFlash*.28})`;ctx.fillRect(0,0,canvas.width,canvas.height)}if(birdAlert>0){ctx.fillStyle='#2a2639dd';ctx.fillRect(0,portrait?70:64,canvas.width,portrait?52:44);ctx.fillStyle='#ffdb92';ctx.font=`800 ${portrait?17:18}px system-ui`;ctx.textAlign='center';ctx.fillText('THE SHADOW BIRD STOLE YOUR STONE!',canvas.width/2,portrait?103:92)}ctx.fillStyle='#fff4dc';ctx.shadowColor='#122323';ctx.shadowBlur=7;ctx.font=`800 ${portrait?18:16}px system-ui`;ctx.textAlign='center';ctx.fillText('HIT THE GOLD EMBLEM',canvas.width/2,portrait?40:38);ctx.shadowBlur=0}
function loop(time){let dt=Math.min((time-last)/1000||0,.033);last=time;step(dt);draw();requestAnimationFrame(loop)}
$('#retryBtn').addEventListener('click',()=>setLevel(level));$('#nextBtn').addEventListener('click',()=>setLevel(won?Math.min(level+1,levels.length-1):level));$('#levelButtons').addEventListener('click',e=>{let b=e.target.closest('[data-level]');if(b&&!b.disabled)setLevel(Number(b.dataset.level))});$('#soundBtn').addEventListener('click',e=>{sound=!sound;e.currentTarget.textContent=sound?'♪':'♪̸';e.currentTarget.setAttribute('aria-label',sound?'Mute sound':'Unmute sound')});$('#helpBtn').onclick=()=>$('#help').showModal();$('#closeHelp').onclick=$('#playBtn').onclick=()=>$('#help').close();function toggleExpanded(force){let on=force??!document.querySelector('.arena-wrap').classList.contains('expanded');document.querySelector('.arena-wrap').classList.toggle('expanded',on);document.body.classList.toggle('game-expanded',on);setCanvasMode()}$('#fullBtn').onclick=()=>toggleExpanded();$('#exitExpanded').onclick=()=>toggleExpanded(false);$('#expandedRetry').onclick=()=>setLevel(level);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#help').open)$('#help').close();else if(e.key==='Escape'&&document.querySelector('.arena-wrap').classList.contains('expanded'))toggleExpanded(false);if(e.key.toLowerCase()==='r'&&!$('#help').open)setLevel(level)});
setLevel(0);requestAnimationFrame(loop);
